// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller

import { application } from "./application"

import AttachmentController from "./attachment_controller.js"
application.register("attachment", AttachmentController)

import CompareFilesController from "./compare_files_controller.js"
application.register("compare-files", CompareFilesController)

import ComparisonResultsController from "./comparison_results_controller.js"
application.register("comparison-results", ComparisonResultsController)

import ErrorsController from "./errors_controller.js"
application.register("errors", ErrorsController)

import ReportsController from "./reports_controller.js"
application.register("reports", ReportsController)
